#!/usr/bin/env bash
# CDS test runner.
#
# Three things are proven here, and the render proof is NOT optional:
#   1. plugin structure — checks/* (schema, structure, links, reference, consistency)
#   2. correctness      — property-based lint over the live elements YAML
#   3. render proof      — the generated visual artifacts MUST exist; the galleries
#                          are (re)assembled over them.
#
# Tiers 1 and 2 are deterministic (pure scripts, no LLM). Tier 3's artifacts
# cannot be produced by a shell script — they are generated by running the
# plugin's own skills via the `cds-render-proof` workflow, which writes into the
# gitignored visual-proof-out/. This runner does NOT regenerate them (only the
# workflow can); it FAILS if they are absent, so a green run can never hide a
# missing render proof. The workflow is the single regenerate -> verify ->
# assemble entry; this script is the deterministic gate.
#
# Usage:  ./run-tests.sh [elements.yaml]
# Env:    CUSTOMIZABLE_DESIGN_SYSTEM_ELEMENTS overrides the YAML path.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
YAML="${1:-${CUSTOMIZABLE_DESIGN_SYSTEM_ELEMENTS:-$DIR/../setup/customizable-design-elements.yaml}}"
OUT="$DIR/visual-proof-out"

echo "elements YAML: $YAML"
echo
echo "▶ 1/3  plugin structure — discover & run checks/* (schema, structure, links, reference, consistency)"
python3 "$DIR/check-plugin.py"
echo
echo "▶ 2/3  correctness — property-based lint (schema, integrity, aliases, from_palette, coverage)"
python3 "$DIR/../validation/lint-elements.py" "$YAML"
echo
echo "▶ 3/3  render proof — verify generated artifacts exist, then assemble galleries"
if [ -d "$OUT/styles" ] && [ -d "$OUT/shapes" ] && [ -n "$(ls -A "$OUT/shapes")" ]; then
  python3 "$DIR/assemble.py"
  echo "  open $OUT/index.html (components, shapes, landing) — switch theme/mode live."
else
  echo "  ✗ render artifacts missing under $OUT" >&2
  echo "    Generate them with the cds-render-proof workflow (it regenerates ->" >&2
  echo "    verifies -> assembles into visual-proof-out/), then re-run this script." >&2
  exit 1
fi
echo
echo "✓ All tiers passed (structure, correctness, render proof)."
