#!/usr/bin/env bash
# CDS test runner.
#
# Two deterministic tiers run here (pure scripts, no LLM):
#   1. plugin structure — checks/* (schema, structure, links, reference, consistency)
#   2. correctness      — property-based lint over the live elements YAML
#
# The VISUAL render-proof (does the design system actually produce good UI?) is
# NOT deterministic — it is generated by running the plugin's own skills via the
# `cds-render-proof` workflow, then viewed with `render/assemble.py`. That tier
# cannot be reproduced by a shell script, so it lives separately under render/.
#
# Usage:  ./run-tests.sh [elements.yaml]
# Env:    CUSTOMIZABLE_DESIGN_SYSTEM_ELEMENTS overrides the YAML path.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
YAML="${1:-${CUSTOMIZABLE_DESIGN_SYSTEM_ELEMENTS:-$DIR/../setup/customizable-design-elements.yaml}}"

echo "elements YAML: $YAML"
echo
echo "▶ 1/2  plugin structure — discover & run checks/* (schema, structure, links, reference, consistency)"
python3 "$DIR/check-plugin.py"
echo
echo "▶ 2/2  correctness — property-based lint (schema, integrity, aliases, from_palette, coverage)"
python3 "$DIR/../validation/lint-elements.py" "$YAML"
echo
echo "✓ Deterministic tiers passed."
echo
echo "Visual render-proof (separate, skill-driven):"
if [ -d "$DIR/render/styles" ] && [ -n "$(ls -A "$DIR/render/shapes" 2>/dev/null)" ]; then
  python3 "$DIR/render/assemble.py"
  echo "  open $DIR/render/index.html (components, shapes, landing) — switch theme/mode live."
else
  echo "  render artifacts not present. Generate them with the cds-render-proof workflow,"
  echo "  then run: python3 $DIR/render/assemble.py"
fi
